export default {
    about_us:'About Us',
    contact_details:'Contact Details',
    email:'Email :',
    phone:'Phone :',
    driver_account_approve_err:'Your account is not approved yet as rider.',
    account_not_exsist:'Your account does not exist as rider.',
    driver_ride_complete_status:' RIdernhas Completed your delivery. your booking id is',
    please_wait:'Calculating your delivery fare',
    on_trip:'On Trip',
    complete_trip:'COMPLETE TRIP',
    account_successful_done:'Your account has been successfully created and waiting for approve confirmation by admin.',
    image_size_error:'Image Size should not be greater than 2mb.',
    password_blank_error:'Password can\'t be blank.',
    password_complexity_alphabet:'Password must consists of at least 1 alphanumeric characters and 8-15 length.',
    password_complexity_complex:'Password must be atleast 1 Capital letter,1 small-case letter, 1 digit and 1 special character with 6-10 length.',
    driver_registration:'Rider Registration',
    first_name:'First Name',
    first_name_error:'Please enter your first name',
    last_name:'Last Name',
    last_name_error:'Please enter your last name',
    email:'Email',
    email_blank_error:'Please enter a valid email address',
    mobile:'Mobile Number',
    mobile_no_blank_error:'Please enter mobile number',
    password:'Password',
    confrim_password:'Confirm Password',
    password_not_match:'Password does not match',
    vehicle_model_name:'Bike Model Name',
    vehicle_model_name_blank_error:'Bike Name Can\'t be blank',
    vehicle_reg_no:'Bike Registration Number',
    vehicle_number_blank_err:'Bike number Can\'t be blank',
    upload_driving_lisence:'Upload your Driving License',
    image_size_warning:'(Image size: Max 2 MB)',
    reg_no:'Register Now',
    update_profile:'Update Profile',
    valid_mobile_number:'Please enter a valid mobile number',
    update_now:'Update Now',
    no_notification:'No notification found',
    forgot_password:'Forgot Password?',
    valid_email_err:'Please enter a valid email address',
    send_email:'Send Email',
    enter_code:'Enter the code',
    submit:'Submit',
    change_password:'Change Password ?',
    old_password:'Old Password',
    old_password_err:'Please enter a old password',
    new_password:'New Password',
    new_password_err:'Please enter a new password',
    update:'Update',
    login:'Login',
    booking_request:'Booking Requests',
    profile_settings:'Profile Settings',
    incomeText:"My Earnings",
    my_bookings:'My Transactions',
    my_ref:'My Referrals',
    my_commisions:'My Commisions',
    about_us:'Support',
    sign_out:'Log out',
    rider_ride_cancel_text:'Sender has cancelled the delivery',
    mobile_no_found:'Mobile Number Not found',
    otp_error:'Please enter the correct OTP',
    driver_journey_err:'Rider started your delivery. your booking id is',
    on_trip:'On Trip',
    wait_for_rider:'WAIT FOR SENDER',
    rider_notified:'Sender has been notifed',
    start_trip:'START TRIP',
    cancel_reson_1:'Unable to Contact Rider',
    cancel_reson_2:'Bike is not moving in my direction',
    cancel_reson_3:'My reason is not listed',
    cancel_reson_4:'Rider Denied duty',
    cancel_reson_5:'Bike is not coming on expected time',
    api_error:'Google places API Error',
    accept_booking_request:'Accept Your Booking Request',
    pickup_location:'pickup location',
    drop_location:'Recipient location',
    ignore_text:'Ignore',
    modal_close:'Modal has been closed.',
    alert_text:'Alert',
    ignore_job_title:'Do you want to ignore this job?',
    cancel:'Cancel',
    ok:'OK',
    accept:'Accept',
    task_list:'New Orders',
    rider_not_here:'Your delivery new order will appear here ',
    booking_request_rejected:'Your booking request has rejected by requested rider',
    driver_requested_for_payment:'Rider has requested for payment. your booking id is',
    request_payment:'REQUEST PAYMENT',
    my_rides:'My Transactions',
    password_reset_link:'A Password Reset Link sent to your email please check and reset your New Password.',
    notification:'Notifications',
    chat_blank:'please write something...',
    send_msg:', sent a message to you: \n',
    driver:'Rider',
    chat_history_not_found:'No chat history found',
    chat:'Chat',
    send:'Send',
    type_messege:'Type your messege',
    photo_upload_action_sheet_title:'Choose a Media Type ?',
    camera:'Camera',
    galery:'Gallery',
    cancel:'Cancel',
    yes:'Yes',
    password_change:'You Password successfully updated',
    password_not_match:'password does not match',
    confrim:'Confrimation',
    delete_account:'Do you want to delete your account ?',
    my_profile:'My Profile',
    active_status:'Active Status',
    profile_details:'Profile Details',
    location:'Location',
    mobile_no:'Mobile Number',
    preffered_lang:'Preferred Language',
    lang:'English',
    delete_account:'Delete Account',
    payment_info:'Sender Payment Information',
    booking_details:'My Bookings Details',
    you_rate_text:'You have been rated',
    no_rated_text:'You have no rating',
    bill_details:'Bill Details',
    your_trip:'Your Trip',
    total_bill:'Total Bill',
    include_tax:'Includes all Taxes',
    total_payable:'Due Payment',
    go_to_booking:'Go to Booking',
    my_booking:'Transactions',
    job_ignore:'Do you want to ignore this job?',
    show_modal:'Show Modal',
    notification_title:'Gixtic Notification',
    register:'Register',
    today:'Today\'s Earning',
    thismonth:'This Month\'s Earning',
    totalearning:'Total Earning',
    convenienceFee:'Convenience Fee',
    paymentStatus:'Payment Status',
    payment_mode:'Payment Mode',
    customer_payable:'Sender Payable',
    discount_amount:'Discount Amount',
    CardPaymentAmount:'Pay by card -',
    CashPaymentAmount:'Pay by cash -',
    WalletPayment:'Pay by wallet -',
    android_channel: 'Gixtic Notifications'
}